language: android

#env:
# matrix:
#    - ANDROID_TARGET=android-18 ANDROID_ABI=armeabi-v7a
#  global:
#   # install timeout in minutes (2 minutes by default)
#    - ADB_INSTALL_TIMEOUT=8

addons:
  apt_packages:
    - pandoc
  #artifacts:
  #  paths:
  #    - $(git ls-files -o | grep build/outputs | tr "\n" ":")

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23
    - extra-android-support

    # Specify at least one system image, if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-23
    #- sys-img-x86-android-17

# Emulator Management: Create, Start
before_script:
  - echo no | android create avd --force --name test --target android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -no-boot-anim &

script:
    - ./gradlew check --continue
    - android-wait-for-emulator
    - adb devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedAndroidTest -PdisablePreDex --continue
#  - rm /home/travis/.gradle/caches/2.8/plugin-resolution/cache.properties.lock

after_failure:
  # print lint results details
  - for f in app/build/outputs/lint-results.html; do pandoc $f -t plain; done
  - pandoc app/build/reports/tests/debug/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'